"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_controller_1 = require("../controllers/auth.controller");
const router = express_1.Router();
router.post('/send-otp', auth_controller_1.sendOTP);
router.post('/verify-otp', auth_controller_1.verifyOTP);
router.post('/update-user-details', auth_controller_1.updateUserDetails);
router.post('/refresh-token', auth_controller_1.refreshToken);
exports.default = router;
